// Copyright (C) 1991-2010 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II Version 10.0 (Build Build 262 08/18/2010)
// Created on Thu Apr 21 19:40:59 2011

wr_sdram wr_sdram_inst
(
	.reset_n(reset_n_sig) ,	// input  reset_n_sig
	.clk(clk_sig) ,	// input  clk_sig
	.vs(vs_sig) ,	// input  vs_sig
	.field(field_sig) ,	// input  field_sig
	.rdusedw_fifo(rdusedw_fifo_sig) ,	// input [9:0] rdusedw_fifo_sig
	.indata(indata_sig) ,	// input [15:0] indata_sig
	.rd_en_fifo(rd_en_fifo_sig) ,	// output  rd_en_fifo_sig
	.wr_req(wr_req_sig) ,	// output  wr_req_sig
	.wr_ack(wr_ack_sig) ,	// input  wr_ack_sig
	.burst_data(burst_data_sig) ,	// output [15:0] burst_data_sig
	.burst_length(burst_length_sig) ,	// output [8:0] burst_length_sig
	.burst_address(burst_address_sig) 	// output [21:0] burst_address_sig
);

defparam wr_sdram_inst.IDLE = 'b000001;
defparam wr_sdram_inst.WR_REQ = 'b000010;
defparam wr_sdram_inst.BURST = 'b000100;
defparam wr_sdram_inst.STATE_NOP = 'b001000;
