// Copyright (C) 1991-2010 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II Version 10.0 (Build Build 262 08/18/2010)
// Created on Thu Apr 21 19:15:45 2011

rd_sdram rd_sdram_inst
(
	.clk_108m(clk_108m_sig) ,	// input  clk_108m_sig
	.reset_n(reset_n_sig) ,	// input  reset_n_sig
	.rd_data(rd_data_sig) ,	// input [15:0] rd_data_sig
	.rd_data_valid(rd_data_valid_sig) ,	// input  rd_data_valid_sig
	.vs(vs_sig) ,	// input  vs_sig
	.rd_req(rd_req_sig) ,	// output  rd_req_sig
	.rd_data_length(rd_data_length_sig) ,	// output [8:0] rd_data_length_sig
	.rd_addr_base(rd_addr_base_sig) ,	// output [21:0] rd_addr_base_sig
	.vs_pos(vs_pos_sig) ,	// output  vs_pos_sig
	.wrusedw_fifo(wrusedw_fifo_sig) ,	// input [9:0] wrusedw_fifo_sig
	.wr_en_fifo(wr_en_fifo_sig) ,	// output  wr_en_fifo_sig
	.din_fifo(din_fifo_sig) 	// output [15:0] din_fifo_sig
);

defparam rd_sdram_inst.INTTIAL = 'b10000;
defparam rd_sdram_inst.IDLE = 'b00001;
defparam rd_sdram_inst.RD_REQ = 'b00010;
defparam rd_sdram_inst.RD_BURST = 'b00100;
defparam rd_sdram_inst.FSM_AROUND = 'b01000;
